spring:
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/galop
      username: postgres
      password: 123456

      # 连接池
      initialSize: 1
      maxActive: 20
      maxWait: 60000
      minIdle: 1

      # 异步初始化
      asyncInit: true

      # 缓存 PSCache
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

      # 检查间隔与最短连接时间
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

      # 检测连接是否安全有效
      validationQuery: select 1
      validationQueryTimeout: 5
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true

      # 监控
      filters: stat,wall,slf4j

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
#
#  data:
#    redis:
#      repositories:
#        enabled: true
#  redis:
#    # 数据库索引
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    # 连接超时时间
#    timeout: 5000
#
## 邮箱验证码有效时间/分钟
#code:
#  expiration: 5
#
## 登录图形验证码有效时间/分钟
#loginCode:
#  expiration: 2
#
## 密码加密传输，前端公钥加密，后端私钥解密
#rsa:
#  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==
#
## jwt
#jwt:
#  header: Authorization
#
#  # 令牌前缀
#  token-start-with: Bearer
#
#  # 必须使用最少 88 位的 Base64 对该令牌进行编码
#  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
#
#  # 令牌过期时间 此处单位/毫秒 ，默认 2 小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
#  token-validity-in-seconds: 7200000
#
#  # 在线用户 key
#  online-key: online-token
#
#  # 验证码
#  code-key: code-key
#
## 文件存储路径
#file:
#  path: D:\IdeaProjects\galop-server\file\
#  avatar: D:\IdeaProjects\galop-server\avatar\
#  # 文件大小 /M
#  maxSize: 100
#  avatarMaxSize: 5