server:
  ssl:
    key-store: classpath:galop.keystore
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: galop

spring:
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/galop
      username: postgres
      password: 123456

      # 连接池
      initialSize: 1
      maxActive: 20
      maxWait: 60000
      minIdle: 1

      # 异步初始化
      asyncInit: true

      # 缓存 PSCache
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

      # 检查间隔与最短连接时间
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

      # 检测连接是否安全有效
      validationQuery: select 1
      validationQueryTimeout: 5
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true

      # 监控
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 连接堆栈跟踪
          connection-stack-trace-enable: true
          db-type: postgresql
          log-slow-sql: true
          # 合并不同参数 SQL
          merge-sql: true
          # 执行时间大于 1 秒为慢 SQL
          slow-sql-millis: 1000
      filters: wall,slf4j

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      repositories:
        enabled: true

  redis:
    # 数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间
    timeout: 5000

  servlet:
    multipart:
      enabled: true
      location: D:\IdeaProjects\galop-server\file\

  mail:
    host: smtp.qq.com
    username: 1018729292@qq.com


# 邮箱验证码有效时间/分钟
code:
  expiration: 5

# 登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

# jwt
jwt:
  header: Authorization

  # 令牌前缀
  token-start-with: Bearer

  # 必须使用最少 88 位的 Base64 对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=

  # 令牌过期时间 此处单位/毫秒 ，默认 2 小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000

  # 在线用户 key
  online-key: online-token

  # 验证码
  code-key: code-key

# 文件存储路径
file:
  path: D:\IdeaProjects\galop-server\file\
  avatar: D:\IdeaProjects\galop-server\avatar\

  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
